### ISSUE TITLE
Question: what's the best way to implement daily limit of new flashcards

### ISSUE THREAD

**Issue by gitStanda** [open-spaced-repetition/dart-fsrs#16]
**Hey, beginner dev here! 👋**

### Question
I'm right now working on a flashcard app and I want to let the user give the option to set a daily limit of new cards, for example 20. 
And I was wondering, what's the best & simplest way to implement this?

### Current setup
I'm using SQLite to store and retrieve the decks & flashcards. 
My flashcard model looks something like this & I save the card to the SQLite as json (TEXT):

`
class Flashcard {
String front,
String back,
Card card, // dart-fsrs Card model
.
.
}
`
### Possible approach
Here's how I currently see it:
- One way to possibly solve this would be to have some repository SQL method -> something like "watchDueCards" or "getDueCards" and the SQL would take care of everything, but I'm not very proficient in SQL.
- ... or it could be done with Programmatic Approach, but not sure how 

### Questions
- Are there any best practices or alternative approaches I should consider for implementing this feature? 

if not: 
- Which approach would be more efficient and easier to maintain in the long run?

if SQL:
- How would you write the SQL query to enforce a daily limit on new cards?

**Thanks in advance for your help!**

**Comment by ishiko732** [comment]
You need a table structure similar to `Deck`, designed to store `FSRS parameters` and `daily limit`. There is a one-to-many relationship between `Deck` and `FlashCard`.

You can refer to the following repository:
- https://github.com/ishiko732/ts-fsrs-demo/blob/main/src/prisma/schema.prisma
- https://github.com/ishiko732/ts-fsrs-demo/blob/fb5cb86cbd44cff37b84bcc92c549e6654879fec/src/prisma/schema.prisma#L57-L66

**Comment by gitStanda** [comment]
> You need a table structure similar to `Deck`, designed to store `FSRS parameters` and `daily limit`. There is a one-to-many relationship between `Deck` and `FlashCard`.
> 
> You can refer to the following repository:
> 
> * https://github.com/ishiko732/ts-fsrs-demo/blob/main/src/prisma/schema.prisma
> * https://github.com/ishiko732/ts-fsrs-demo/blob/fb5cb86cbd44cff37b84bcc92c549e6654879fec/src/prisma/schema.prisma#L57-L66

My bad, I wasn't specific enough in my question. I already have a Deck model and that's where I will save the daily limit. Didn't think of saving FSRS parameters there, thanks a lot for the idea! 

However, I am not sure how to use the daily limit set by the user to make sure he only gets the correct amount of new cards per day. Currently, I can easily retrieve all due cards and exclude `newState` cards in SQLite. Here’s a rough idea of what it looks like (in pseudocode):

It would look something like this (pseudocode):
**watchDueCards(String deckId)**
```
return _db.watch(
'''
SELECT *
FROM flashcards
WHERE deck_id = ? AND
card->>'State' != 'newState' AND -- COMMENT: ->> should work same as json_extract
card->>'due'  <= DATETIME('now')
''',
parameters: [deckId],) ...
```

The problem is figuring out how to add, say, 20 new cards (based on the user's `deck.dailyLimit`) on top of the existing due cards, and ensure that the same 20 cards are returned each time the function is called that day.

I checked out the TypeScript example you provided (thanks again for that! Might be very useful later, didn't know this existed), but since I’m not familiar with TypeScript, I couldn't find a relevant solution.

Any advice on how to approach this?

I really appreciate the help!

**Comment by ishiko732** [comment]
For retrieving cards in other states, you can refer to the following SQL example:

```sql
select *
from Card
where did=:deckId and ( state not in [State.New,State.Review] or ( state = State.Review and due <= today_start ) )
```
https://github.com/ishiko732/ts-fsrs-demo/blob/fb5cb86cbd44cff37b84bcc92c549e6654879fec/src/lib/reviews/deck/retriever.ts#L298-L326

**Comment by gitStanda** [comment]
> > I am not sure how to use the daily limit set by the user to make sure he only gets the correct amount of new cards per day.
> 
> You need a `logs` table to record card review information. To fetch cards studied on a given day, you can filter by start and end times of the day, and a state of `New`. For instance, using a `revlog` table, you can retrieve the number of new cards studied that day, which can then be adjusted based on the user-specified `daily limit`.
> 
> ex :
> 
> ```sql
> select *  -- count(*)
> from Revlog
> where uid=:uid and did=:deckId and review between (today_start,today_end) and state = State.New
> ```
> 
> https://github.com/ishiko732/ts-fsrs-demo/blob/fb5cb86cbd44cff37b84bcc92c549e6654879fec/src/lib/reviews/deck/retriever.ts#L413-L431

I see, thank you! I'm not sure but I suppose I know how to proceed now.

I don't think I even need a reviewlog or record log item, right? I can achieve the same result with something like:
```ts
select *  -- count(*)
from Card -- Card should have last_review parameter
where uid=:uid and did=:deckId and last_review between (today_start,today_end) and state = State.New
```
This way, I can simply show the user their remaining cards for the day as:
- [count(dueNotNewCards) + count(dueNewCards)]

When the user reviews cards, I'll continue showing random cards from the deck until the remaining card count reaches zero.

Did I understand that correctly? Your second SQL query makes sense, and I’ll definitely use it!

**Comment by ishiko732** [comment]
> I can achieve the same result with something like:
> 
> ```sql
> select *  -- count(*)
> from Card -- Card should have last_review parameter
> where uid=:uid and did=:deckId and last_review between (today_start,today_end) and state = State.New
> ```

I think that's fine. Incidentally, it is somewhat necessary to record user review data in the revlog to facilitate the use of https://github.com/open-spaced-repetition/fsrs-optimizer for parameter optimization.

**Comment by gitStanda** [comment]
> > I can achieve the same result with something like:
> > ```sql
> > select *  -- count(*)
> > from Card -- Card should have last_review parameter
> > where uid=:uid and did=:deckId and last_review between (today_start,today_end) and state = State.New
> > ```
> 
> I think that's fine. Incidentally, it is somewhat necessary to record user review data in the revlog to facilitate the use of https://github.com/open-spaced-repetition/fsrs-optimizer for parameter optimization.

Mhmm. Didn't know that. I saw there _might_ be dart-optimizer coming as well so I might actually store the user review data as well, just so I can use it later - in case it gets implemented.

I think I also read somewhere that the FSRS with default parameters is still better than SuperMemo 2 for example, although I am not sure where I read that.

**Comment by ishiko732** [comment]
Oh, right. The reason I don't use the `card` to query new cards is that, currently, the TS-FSRS demo is designed for future implementation where one note corresponds to multiple cards. Therefore, creating a new note does not create a card; cards are only created during the first scheduling. This is why I must use the `revlog` to determine the number of new cards needed.

**Comment by gitStanda** [comment]
> Oh, right. The reason I don't use the `card` to query new cards is that, currently, the TS-FSRS demo is designed for future implementation where one note corresponds to multiple cards. Therefore, creating a new note does not create a card; cards are only created during the first scheduling. This is why I must use the `revlog` to determine the number of new cards needed.

Got it, that makes sense.

Before I wrap this up & close this, do you have any other tips or insights you'd recommend? I really appreciate all your help—there’s so much I didn’t even realize until now, so thank you for all the valuable advice! 😄

**Comment by ishiko732** [comment]
> do you have any other tips or insights you'd recommend?

The order of card drawing may affect the user experience. For details, please refer to: [https://github.com/open-spaced-repetition/fsrs4anki/pull/634](https://github.com/open-spaced-repetition/fsrs4anki/pull/634).

**Comment by gitStanda** [comment]
> > do you have any other tips or insights you'd recommend?
> 
> The order of card drawing may affect the user experience. For details, please refer to: [open-spaced-repetition/fsrs4anki#634](https://github.com/open-spaced-repetition/fsrs4anki/pull/634).

I see, that was actually another question I wanted to ask! I was sorting by _due_.
Well, now I know I should look through all FSRS repos & their Issues before asking.

I guess I will simply sort the "non-new" by `difficulty_asc` and insert the "newState" cards randomly.
Solved, closing.

**Comment by gitStanda** [comment]
> > I can achieve the same result with something like:
> > ```sql
> > select *  -- count(*)
> > from Card -- Card should have last_review parameter
> > where uid=:uid and did=:deckId and last_review between (today_start,today_end) and state = State.New
> > ```
> 
> I think that's fine. Incidentally, it is somewhat necessary to record user review data in the revlog to facilitate the use of https://github.com/open-spaced-repetition/fsrs-optimizer for parameter optimization.

Realized I can't do this as the `state` won't be "newState" anymore (once it's studied). So I will need to store revlog as well in order to implement new cards daily limit 🥲 Thought this is gonna be simpler. 
I also realised watching a Stream of due cards in review session isn't as easy as I initially hoped, but I opened another question regarding that. I'll try my best not to give up lol
